name: Build CodeVisualizer for All Platforms

on:
  push:
    tags:
      - 'v*'  # Запускается при создании тега версии (v1.0.0)
  workflow_dispatch:  # Можно запустить вручную

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact_name: CodeVisualizer-Windows
            executable_name: CodeVisualizer.exe
          - os: ubuntu-latest
            artifact_name: CodeVisualizer-Linux
            executable_name: CodeVisualizer
          - os: macos-latest
            artifact_name: CodeVisualizer-macOS
            executable_name: CodeVisualizer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libegl1-mesa libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyQt6-QScintilla pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onedir --windowed --name CodeVisualizer src/main.py

    - name: Create portable package (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd dist
        Compress-Archive -Path CodeVisualizer -DestinationPath CodeVisualizer-Windows.zip

    - name: Create portable package (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        cd dist
        tar -czf CodeVisualizer-${{ matrix.os }}.tar.gz CodeVisualizer/

    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/CodeVisualizer-Windows.zip

    - name: Upload Linux artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/CodeVisualizer-ubuntu-latest.tar.gz

    - name: Upload macOS artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/CodeVisualizer-macos-latest.tar.gz
